@Chat.App.API_HostAddress = http://localhost:5081

GET {{Chat.App.API_HostAddress}}/api/
Accept: application/json

###

GET {{Chat.App.API_HostAddress}}/api/conversations
Accept: application/json

###

POST {{Chat.App.API_HostAddress}}/api/chat
Content-Type: application/json
Accept: text/event-stream

{
  "conversationId": null,
  "message": "My name is Ashish."
}
###

POST {{Chat.App.API_HostAddress}}/api/chat
Content-Type: application/json
Accept: text/event-stream

{
  "conversationId": "71f20f16-13b0-420d-a9df-b936681583b3",
  "message": "What is my name?"
}

###

@id = 71f20f16-13b0-420d-a9df-b936681583b3

GET {{Chat.App.API_HostAddress}}/api/conversations/{{id}}
Accept: application/json

###

PATCH {{Chat.App.API_HostAddress}}/api/conversations/{{id}}
Content-Type: application/json

{
  "title": "My First Chat"
}

###

DELETE {{Chat.App.API_HostAddress}}/api/conversations/{{id}}
Accept: application/json

###